### ISSUE TITLE
Is FRLG+ available for iOS Delta emulator?

### ISSUE THREAD

**Issue by Supsight** [Deokishisu/FRLG-Plus#41]
Hey there! 
I‘m wondering if your game is possible to play on Delta Emulator on iOS. I tried to download it and implement into Delta but it didnt work. 
thank you and greetings
Supsight

**Comment by Deokishisu** [comment]
Delta can't play patch files. If you didn't patch the .bps file onto a FireRed ROM (which you have to get separately) then it will not work. I don't own any Apple devices, but if the emulator is the least bit accurate, FRLG+ should work on it. I'm going to close this because this is fundamentally an emulator question and not a FRLG+ question.
